spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6l8jnvtskes73ejs4m0-a.oregon-postgres.render.com/haapsalu_database
spring.datasource.username=haapsalu_user
spring.datasource.password=m8VHT2VNKJbhbNdYZfSVn6LZJThDLgpE